[package]
name = "advent-2020"
version = "0.1.0"
authors = ["jlricon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc = "15.0.0"
itertools = "0.9.0"